const fs = require('fs');
const path = require('path');
const juice = require('juice');
const pandoc = require('node-pandoc');
const postcss = require('postcss');
const cssVariables = require('postcss-css-variables');
const util = require('util');

const pandocPromise = util.promisify(pandoc);

/**
 * Main function to build the styled HTML component and optional multi-format outputs.
 */
async function buildComponent(options) {
    const { 
        inputFile, 
        themeName, 
        scopeClass = 'living-syllabus', 
        outputDir = null,
        formats = ['html'] // e.g., ['html', 'pdf', 'docx']
    } = options;

    console.log(`\n🏗️  Compiling [${inputFile}] with [${themeName.toUpperCase()}] Theme`);

    if (!fs.existsSync(inputFile)) {
        console.error(`❌ Error: Source file '${inputFile}' not found.`);
        return;
    }

    const baseName = path.basename(inputFile, path.extname(inputFile));
    
    // Determine output directory
    let finalOutputDir = outputDir;
    if (!finalOutputDir) {
        // If not specified, default to putting it next to the source file
        finalOutputDir = path.dirname(inputFile);
    }
    
    // Ensure output directory exists
    if (!fs.existsSync(finalOutputDir)) {
        fs.mkdirSync(finalOutputDir, { recursive: true });
    }

    // Resolve theme file path
    let cssFile = `${themeName}.css`;
    if (!fs.existsSync(cssFile)) {
        if (fs.existsSync(path.join(__dirname, 'themes', cssFile))) {
             cssFile = path.join(__dirname, 'themes', cssFile);
        } else {
            console.error(`❌ Error: Theme file '${themeName}.css' not found in root or /themes.`);
            return;
        }
    }

    const fileExt = path.extname(inputFile).toLowerCase();
    if (fileExt !== '.md' && fileExt !== '.markdown' && fileExt !== '.docx') {
        console.error(`❌ Error: Unsupported file type '${fileExt}'. Please use .md or .docx`);
        return;
    }

    const isMarkdown = fileExt === '.md' || fileExt === '.markdown';
    const sourceFormat = isMarkdown ? 'gfm' : 'docx';

    // MULTI-FORMAT SUPPORT
    for (const format of formats) {
        const outputFile = path.join(finalOutputDir, `${baseName}_${themeName}.${format}`);
        
        if (format === 'html') {
            console.log(`   ...Building HTML Fragment...`);
            
            // HTML specific pandoc args
            const pandocArgs = `-f ${sourceFormat} -t html5 --wrap=none --section-divs --webtex`;
            
            // CSS Processing
            const rawCss = fs.readFileSync(cssFile, 'utf8');
            const licenseMatch = rawCss.match(/\/\*[\s\S]*?(?:Theme|Copyright|License)[\s\S]*?\*\//i);
            let licenseHeader = ``;
            if (licenseMatch) {
                const cleanText = licenseMatch[0].replace(/\/\*!?/, '').replace(/\*\//, '').trim();
                licenseHeader = `<!-- ${cleanText} -->`;
            }
            
            let sanitizedCss = rawCss.replace(/:host/g, ':root');
            sanitizedCss = sanitizedCss.replace(/url\("data:[^"]+"\)/g, 'none');

            let flatCss = '';
            try {
                const result = await postcss([
                    cssVariables({ preserve: false })
                ]).process(sanitizedCss, { from: cssFile, to: undefined });
                flatCss = result.css;
            } catch (err) {
                console.error('❌ CSS Compilation Error:', err);
                continue;
            }

            try {
                const htmlContent = await pandocPromise(inputFile, pandocArgs);
                const wrappedHtml = `
            <div class="${scopeClass}" style="max-width: 800px; margin: 0 auto; font-family: sans-serif;">
                ${htmlContent}
            </div>
            `;
                const finalHtml = juice.inlineContent(wrappedHtml, flatCss, {
                    applyStyleTags: true,
                    removeStyleTags: true,
                    preserveMediaQueries: false,
                    widthElements: ['table', 'td', 'th']
                });

                const stamp = `<!-- Generated by Living Syllabus on ${new Date().toISOString()} -->\n\n${licenseHeader}\n\n`;
                fs.writeFileSync(outputFile, stamp + finalHtml);
                console.log(`   ✅ Success: ${outputFile}`);
            } catch (err) {
                console.error('❌ HTML Pandoc Error:', err);
            }

        } else if (format === 'pdf' || format === 'docx') {
            console.log(`   ...Building Standalone ${format.toUpperCase()}...`);
            const pandocArgs = `-f ${sourceFormat} -t ${format} -o ${outputFile} --webtex`;
            
            try {
                await pandocPromise(inputFile, pandocArgs);
                console.log(`   ✅ Success: ${outputFile}`);
            } catch (err) {
                console.error(`❌ ${format.toUpperCase()} Pandoc Error:`, err);
                if (format === 'pdf') {
                    console.error(`   (Note: PDF generation requires wkhtmltopdf or a LaTeX engine installed on the system)`);
                }
            }
        }
    }
}

// CLI Execution Support
if (require.main === module) {
    const args = process.argv.slice(2);

    if (args.includes('--help') || args.includes('-h')) {
        console.log(`
Usage: node generate.js <input_file> <theme_name> [scope_class] [--artifact=pdf|docx|both] [--outdir=dist]

Arguments:
  input_file    Path to .md or .docx file
  theme_name    Name of the theme (e.g., 'simple', 'academic')
  scope_class   Optional CSS scope class (default: 'living-syllabus')
  --artifact    Optional standalone artifact to generate (pdf, docx, or both)
  --outdir=DIR  Specify output directory

Examples:
  node generate.js syllabus.md simple
  node generate.js week1.docx academic my-custom-scope --artifact=docx --outdir=dist
        `);
        process.exit(0);
    }

    if (args.length < 2 || args[0].startsWith('--') || args[1].startsWith('--')) {
        console.error("❌ Error: Please provide both an input file and a theme.");
        process.exit(1);
    }

    // Parse options
    const positionalArgs = [];
    const formats = ['html'];
    let outdir = null;

    for (const arg of args) {
        if (arg.startsWith('--artifact=')) {
            const val = arg.split('=')[1].toLowerCase();
            if (val === 'pdf') formats.push('pdf');
            else if (val === 'docx') formats.push('docx');
            else if (val === 'both') formats.push('pdf', 'docx');
        }
        else if (arg === '--pdf') formats.push('pdf'); // Backward compatibility
        else if (arg === '--docx') formats.push('docx'); // Backward compatibility
        else if (arg.startsWith('--outdir=')) outdir = arg.split('=')[1];
        else positionalArgs.push(arg);
    }

    const inputFile = positionalArgs[0];
    const themeName = positionalArgs[1];
    const scopeClass = (positionalArgs[2] || 'living-syllabus').replace(/^\./, '');

    buildComponent({
        inputFile,
        themeName,
        scopeClass,
        outputDir: outdir,
        formats
    });
}

module.exports = { buildComponent };